- name: Demo on pulling aws secrets and parameters
  hosts: localhost
  tasks:
    - name: Pull secret
      debug: msg="{{ lookup('amazon.aws.aws_secret', 'roboshop/all-secrets', region='us-east-1') }}"